version: '3'

services:
    db:
        image: postgres
        
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Admin2022
            POSTGRES_DB: insportify-db1
            POSTGRES_HOST: insportify-db1.cz5lufvg1olp.ca-central-1.rds.amazonaws.com
            POSTGRES_PORT: 5432 

    insportify-app:
        container_name: insportify-app
        build: .
        volumes:
            - .:/app
            - static_volume:/app/static
        networks:
            - db_network
            - web_network


    nginx:
        container_name: nginx
        restart: always
        image: "nginx:latest"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./nginx/insportify.com.crt:/etc/nginx/certs/insportify.com.crt
            - ./nginx/insportify.com.key:/etc/nginx/certs/insportify.com.key
            - static_volume:/app/static
        environment:
            - NGINX_PORT=443
        networks:
            - web_network
        depends_on: 
            - insportify-app

networks:
    db_network:
        driver: bridge
    web_network:
        driver: bridge

volumes:
  static_volume: